Repository boostcampwm-2022/web12-MOJ, pull requests merged in 2022-12, with the labels that each got.

#154 제출 응답이 밀리는 문제 수정 (Close #151)
  scoring-server/src/scoring/scoring.controller.ts
  scoring-server/src/scoring/scoring.service.ts
Labels: bug, BE

#161 docker 빌드 최적화
  scoring-server/.dockerignore
  scoring-server/docker/Dockerfile
Labels: refactor

#165 도커 컨테이너 여러 개 띄울 수 있도록 변경
  scoring-server/docker/run.sh
  scoring-server/src/scoring/scoring.service.ts
Labels: 리뷰요청, BE

#166 도커 컨테이너 여러 개 띄울 수 있도록 변경(dev -> main)
  scoring-server/docker/run.sh
  scoring-server/src/scoring/scoring.service.ts
Labels: BE

#168 페이지네이션 쿼리문 limit, offset으로 변경
  server/src/submissions/submissions.service.ts
Labels: bug, 리뷰요청, BE

#170 Feat/#169
  scoring-server/package.json
  scoring-server/src/app.module.ts
  scoring-server/src/queue/queue.consumer.ts
  scoring-server/src/queue/queue.module.ts
  scoring-server/src/scoring/scoring.controller.spec.ts
  scoring-server/src/scoring/scoring.controller.ts
  scoring-server/src/scoring/scoring.module.ts
  scoring-server/src/scoring/scoring.service.spec.ts
  scoring-server/src/scoring/scoring.service.ts
  scoring-server/yarn.lock
  server/package.json
  server/src/problems/problems.module.ts
  server/src/problems/problems.service.ts
  server/yarn.lock
Labels: BE

#175 22.12.07 작업사항 2
  scoring-server/src/queue/queue.module.ts
  server/src/problems/problems.module.ts
Labels: BE

#178 입출력 예제 줄바꿈, 테케 및 예제 input 빈칸 허용하도록 수정 및 페이지별 타이틀 변경
  client/components/Problem/ProblemContainer.tsx
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/index.tsx
  client/pages/my-problem/new.tsx
  client/pages/my-problem/tc/[id].tsx
  client/pages/problem/[id].tsx
  client/pages/status/[id].tsx
  client/pages/status/index.tsx
  server/src/problems/dtos/create-problem.dto.ts
  server/src/problems/dtos/post-testcase.dto.ts
  server/src/problems/dtos/update-problem.dto.ts
  server/src/problems/problems.service.ts
Labels: bug, refactor

#184 refactor: 채점 서버 큐 (Close #183)
  scoring-server/src/queue/queue.consumer.ts
Labels: refactor, BE

#191 기능 개발 및 버그 수정
  client/components/Problem/ProblemContainer.tsx
  client/components/problemList.tsx
  client/global.d.ts
  client/package.json
  client/pages/index.tsx
  client/pages/status/[id].tsx
  client/pages/status/index.tsx
  client/yarn.lock
  server/src/problems/problems.service.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.service.ts
Labels: FE, BE, API

#192 22.12.12 작업사항
  client/components/Problem/ProblemContainer.tsx
  client/components/problemList.tsx
  client/global.d.ts
  client/package.json
  client/pages/index.tsx
  client/pages/status/[id].tsx
  client/pages/status/index.tsx
  client/yarn.lock
  scoring-server/src/queue/queue.consumer.ts
  server/src/problems/problems.service.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.service.ts
Labels: FE, BE, API

#197 12.13 프론트 작업 (Close #196)
  client/components/GNB/Logo.tsx
  client/components/GNB/index.tsx
  client/components/Problem/ProblemContainer.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/styles/style.ts
Labels: FE

#199 22.12.13 프론트 작업
  client/components/GNB/Logo.tsx
  client/components/GNB/index.tsx
  client/components/Problem/ProblemContainer.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/styles/style.ts
Labels: FE

#206 페이로드 8mb 제한 및 API 호출 수 제한
  client/pages/my-problem/new.tsx
  server/package.json
  server/src/main.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.module.ts
  server/src/problems/throttler-behind-proxy.guard.ts
  server/yarn.lock
Labels: BE, API

#218 fix: 채점 중간에 오류날 때 임시 파일 제거하도록 수정 (Close #217)
  scoring-server/src/scoring/scoring.service.ts
Labels: bug, BE

#219 refactor: 사용하지 않는 변수, import 제거 (Close #179)
  client/components/GNB/UserInfo.tsx
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/List/paginator.tsx
  client/components/Modal/DeleteProblemModal.tsx
  client/components/common/IOList/InputContainer.tsx
  client/components/common/IOList/Row.tsx
  client/components/paginator.tsx
  client/components/problemList.tsx
  client/pages/index.tsx
  client/pages/my-problem/new.tsx
  scoring-server/python/run.py
  scoring-server/src/scoring/scoring.service.ts
  server/src/problems/problems.service.ts
  server/src/problems/throttler-behind-proxy.guard.ts
Labels: refactor

#221 22.12.16 작업사항
  client/components/GNB/UserInfo.tsx
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/List/paginator.tsx
  client/components/Modal/DeleteProblemModal.tsx
  client/components/common/IOList/InputContainer.tsx
  client/components/common/IOList/Row.tsx
  client/components/paginator.tsx
  client/components/problemList.tsx
  client/pages/index.tsx
  client/pages/my-problem/new.tsx
  scoring-server/python/run.py
  scoring-server/src/scoring/scoring.service.ts
  server/src/problems/problems.service.ts
  server/src/problems/throttler-behind-proxy.guard.ts
Labels: bug, FE, refactor, BE, API
