Repository boostcampwm-2022/web12-MOJ, pull requests merged in 2022-11, with the labels that each got.

#55 1 공통 - 상단(GNB) #5
  client/.eslintrc.json
  client/components/GNB/Logo.tsx
  client/components/GNB/Menu.tsx
  client/components/GNB/UserInfo.tsx
  client/components/GNB/index.tsx
  client/next.config.js
  client/pages/_app.tsx
  client/pages/api/user/login-status.ts
Labels: 리뷰요청

#56 2. 문제 목록 (#8)
  client/axios.ts
  client/components/paginator.tsx
  client/components/problemList.tsx
  client/components/problemListRow.tsx
  client/pages/api/problem.tsx
  client/pages/index.tsx
Labels: 리뷰요청

#57 22.11.15 작업사항
  client/.eslintrc.json
  client/axios.ts
  client/components/GNB/Logo.tsx
  client/components/GNB/Menu.tsx
  client/components/GNB/UserInfo.tsx
  client/components/GNB/index.tsx
  client/components/paginator.tsx
  client/components/problemList.tsx
  client/components/problemListRow.tsx
  client/next.config.js
  client/pages/_app.tsx
  client/pages/api/problem.tsx
  client/pages/api/user/login-status.ts
  client/pages/index.tsx
Labels: 리뷰요청

#59 4. 채점 현황 (#12)
  client/components/List/index.tsx
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/List/paginator.tsx
  client/components/problemList.tsx
  client/components/problemListRow.tsx
  client/pages/api/submissions.tsx
  client/pages/index.tsx
  client/pages/status/index.tsx
Labels: 리뷰요청

#60 Feat/#7
  client/components/GNB/UserInfo.tsx
  client/components/Problem/CodeContainer.tsx
  client/components/Problem/ProblemContainer.tsx
  client/components/common/Button.tsx
  client/global.d.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/api/problems/[id].ts
  client/pages/api/problems/[id]/submissions.ts
  client/pages/problem/[id].tsx
  client/pages/problem/styles.ts
  client/tsconfig.json
  client/yarn.lock
Labels: 리뷰요청

#61 6. 문제 출제 (#9)
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/svgs/add-file.tsx
  client/components/svgs/delete.tsx
  client/components/svgs/edit.tsx
  client/components/svgs/index.tsx
  client/components/svgs/toggle.tsx
  client/pages/api/problems/index.ts
  client/pages/my-problem/index.tsx
Labels: 리뷰요청

#62 Feat/#11 (close #11)
  client/components/status/StatusList.tsx
  client/pages/api/submissions/[id].ts
  client/pages/status/[id].tsx
Labels: 리뷰요청

#66 6. 문제 출제 (#9) [추가 변경사항]
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/svgs/close.tsx
  client/components/svgs/index.tsx
  client/mock/problems.ts
  client/pages/api/problems/[id].ts
  client/pages/api/problems/[id]/visible.ts
  client/pages/api/problems/index.ts
  client/pages/my-problem/index.tsx
Labels: 리뷰요청

#67 Feat/#13
  client/components/common/Button.tsx
  client/components/common/IOList/InputContainer.tsx
  client/components/common/IOList/Row.tsx
  client/components/common/IOList/index.tsx
  client/components/svgs/index.tsx
  client/components/svgs/removeRow.tsx
  client/global.d.ts
  client/pages/api/problems/[id]/tc.ts
  client/pages/my-problem/tc/[id].tsx
Labels: 리뷰요청

#68 Feat/#7
  client/components/Problem/ProblemContainer.tsx
  client/components/common/IOList/InputContainer.tsx
  client/components/common/IOList/Row.tsx
  client/components/common/IOList/index.tsx
  client/package.json
  client/pages/api/problems/[id].ts
  client/pages/problem/[id].tsx
  client/yarn.lock
Labels: 리뷰요청

#69 22.11.17 작업사항
  .prettierrc
  README.md
  client/components/Editor/wrapperEditor.tsx
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/Problem/ProblemContainer.tsx
  client/components/common/Button.tsx
  client/components/common/IOList/InputContainer.tsx
  client/components/common/IOList/Row.tsx
  client/components/common/IOList/index.tsx
  client/components/svgs/close.tsx
  client/components/svgs/index.tsx
  client/components/svgs/removeRow.tsx
  client/global.d.ts
  client/mock/problems.ts
  client/package.json
  client/pages/api/problems/[id].ts
  client/pages/api/problems/[id]/tc.ts
  client/pages/api/problems/[id]/visible.ts
  client/pages/api/problems/index.ts
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/index.tsx
  client/pages/my-problem/new.tsx
  client/pages/my-problem/tc/[id].tsx
  client/pages/problem/[id].tsx
  client/yarn.lock
  deploy.sh
Labels: 리뷰요청

#73 Refactor/#72
  client/components/Editor/wrapperEditor.tsx
  client/components/GNB/UserInfo.tsx
  client/components/GNB/index.tsx
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/Modal/DeleteProblemModal.tsx
  client/components/Modal/index.tsx
  client/components/common/IOList/Row.tsx
  client/components/common/IOList/index.tsx
  client/components/problemList.tsx
  client/components/status/StatusList.tsx
  client/components/svgs/index.tsx
  client/global.d.ts
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/index.tsx
  client/pages/my-problem/new.tsx
  client/pages/my-problem/tc/[id].tsx
  client/pages/problem/[id].tsx
  client/pages/status/[id].tsx
  client/pages/status/index.tsx
  client/styles/index.ts
  client/styles/modal.ts
  client/styles/style.ts
Labels: 리뷰요청, refactor

#74 22.11.21 작업사항(close #72)
  client/components/Editor/wrapperEditor.tsx
  client/components/GNB/UserInfo.tsx
  client/components/GNB/index.tsx
  client/components/List/list.tsx
  client/components/List/listRow.tsx
  client/components/Modal/DeleteProblemModal.tsx
  client/components/Modal/index.tsx
  client/components/common/IOList/Row.tsx
  client/components/common/IOList/index.tsx
  client/components/problemList.tsx
  client/components/status/StatusList.tsx
  client/components/svgs/index.tsx
  client/global.d.ts
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/index.tsx
  client/pages/my-problem/new.tsx
  client/pages/my-problem/tc/[id].tsx
  client/pages/problem/[id].tsx
  client/pages/status/[id].tsx
  client/pages/status/index.tsx
  client/styles/index.ts
  client/styles/modal.ts
  client/styles/style.ts
Labels: 리뷰요청

#79 Feat/#78 (Close #78)
  server/.gitignore
  server/package.json
  server/src/app.module.ts
  server/src/problems/entities/example.entity.ts
  server/src/problems/entities/problem.entity.ts
  server/src/problems/entities/testcase.entity.ts
  server/src/problems/problems.module.ts
  server/src/submissions/entities/language.entity.ts
  server/src/submissions/entities/result.entity.ts
  server/src/submissions/entities/state.entity.ts
  server/src/submissions/entities/submission.entity.ts
  server/src/submissions/submissions.module.ts
  server/src/users/entities/user.entity.ts
  server/src/users/users.module.ts
  server/yarn.lock
Labels: 리뷰요청

#98 2. POST /github-login (Close #87)
  client/components/GNB/UserInfo.tsx
  client/components/GNB/index.tsx
  client/next.config.js
  client/pages/users/oauth.tsx
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: 리뷰요청, BE, API

#96 3.POST /api/problems (Close #82)
  client/pages/api/problems/index.ts
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/new.tsx
  server/package.json
  server/src/main.ts
  server/src/problems/dtos/create-problem.dto.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.module.ts
  server/src/problems/problems.service.ts
  server/yarn.lock
Labels: 리뷰요청

#103 Refactor (Close #99)
  server/src/main.ts
  server/src/users/dtos/github-login.dto.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: 리뷰요청, BE

#109 3. POST /api/problems 출제자 추가 (close #102)
  client/pages/my-problem/new.tsx
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
Labels: 리뷰요청, FE, BE

#106 8. GET /problems/:id/tc (Close #89)
  client/pages/my-problem/tc/[id].tsx
  server/src/main.ts
  server/src/problems/dtos/get-testcase.dto.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
Labels: 리뷰요청, BE, API

#112 9. POST /problems/:id/tc (close #90 close #111)
  client/pages/my-problem/tc/[id].tsx
  server/src/main.ts
  server/src/problems/dtos/get-testcase.dto.ts
  server/src/problems/dtos/post-testcase.dto.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
Labels: 리뷰요청, FE, BE, API

#117 4. GET /api/problems API 관련 작업
  client/global.d.ts
  client/pages/index.tsx
  client/pages/my-problem/index.tsx
  server/src/problems/entities/problem.entity.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
Labels: FE, BE, API

#119 11. GET /submissions/:id (Close #92)
  client/components/status/StatusList.tsx
  client/global.d.ts
  client/pages/api/v0/submissions/[id].ts
  client/pages/api/v0/user/login-status.ts
  client/pages/status/[id].tsx
  server/src/submissions/entities/submission.entity.ts
  server/src/submissions/submissions.controller.spec.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.module.ts
  server/src/submissions/submissions.service.ts
  server/src/submissions/submissions.spec.ts
Labels: 리뷰요청, BE, API

#120 6. PATCH /api/problems/:id (close #84)
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/index.tsx
  server/src/problems/dtos/update-problem.dto.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
Labels: 리뷰요청, FE, BE, API

#122 feat: Close #85
  server/src/problems/entities/problem.entity.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
Labels: BE, API

#125 22.11.24 작업사항
  client/components/status/StatusList.tsx
  client/global.d.ts
  client/pages/api/v0/submissions.tsx
  client/pages/api/v0/submissions/[id].ts
  client/pages/api/v0/user/login-status.ts
  client/pages/index.tsx
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/index.tsx
  client/pages/status/[id].tsx
  client/pages/status/index.tsx
  server/src/problems/dtos/update-problem.dto.ts
  server/src/problems/entities/problem.entity.ts
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
  server/src/submissions/entities/submission.entity.ts
  server/src/submissions/submissions.controller.spec.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.module.ts
  server/src/submissions/submissions.service.ts
  server/src/submissions/submissions.spec.ts
Labels: 리뷰요청, FE, BE, API

#130 fix: 문제 제출 권한 문제 해결 (Close #129)
  server/src/problems/problems.service.ts
Labels: bug, BE, API

#134 Fix/#133
  client/components/Editor/wrapperEditor.tsx
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/new.tsx
  client/pages/problem/[id].tsx
Labels: bug

#135 Refactor/#110
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: refactor, BE, API

#136 22.11.26 작업사항
  client/components/Editor/wrapperEditor.tsx
  client/pages/my-problem/edit/[id].tsx
  client/pages/my-problem/new.tsx
  client/pages/problem/[id].tsx
  server/src/problems/problems.controller.ts
  server/src/problems/problems.service.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: bug, 리뷰요청

#143 Feat/#142
  scoring-server/src/scoring/scoring.service.ts
  server/src/problems/problems.module.ts
  server/src/problems/problems.service.ts
  server/src/submissions/dtos/post-result.dto.ts
  server/src/submissions/submissions.controller.ts
  server/src/submissions/submissions.module.ts
  server/src/submissions/submissions.service.ts
  server/src/users/users.service.ts
Labels: 리뷰요청, BE, API
